import { StudyResource } from './firebase';

export interface CurriculumOption {
  classLevel: string;
  boards: string[];
  subjects: {
    name: string;
    chapters: string[];
  }[];
}

export const CURRICULUM_DATA: CurriculumOption[] = [
  {
    classLevel: 'Class 10',
    boards: ['CBSE', 'NCERT', 'ICSE', 'State Board'],
    subjects: [
      {
        name: 'Science',
        chapters: [
          'Chemical Reactions and Equations',
          'Acids, Bases and Salts',
          'Metals and Non-metals',
          'Carbon and its Compounds',
          'Life Processes',
          'Control and Coordination',
          'How do Organisms Reproduce?',
          'Heredity and Evolution',
          'Light – Reflection and Refraction',
          'The Human Eye and the Colorful World',
          'Electricity',
          'Magnetic Effects of Electric Current',
          'Our Environment',
        ],
      },
      {
        name: 'Mathematics',
        chapters: [
          'Real Numbers',
          'Polynomials',
          'Pair of Linear Equations in Two Variables',
          'Quadratic Equations',
          'Arithmetic Progressions',
          'Triangles',
          'Coordinate Geometry',
          'Introduction to Trigonometry',
          'Some Applications of Trigonometry',
          'Circles',
          'Areas Related to Circles',
          'Surface Areas and Volumes',
          'Statistics',
          'Probability',
        ],
      },
      {
        name: 'Social Science',
        chapters: [
          'The Rise of Nationalism in Europe',
          'Nationalism in India',
          'Resources and Development',
          'Forest and Wildlife Resources',
          'Water Resources',
          'Agriculture',
          'Power Sharing',
          'Federalism',
          'Development',
          'Sectors of the Indian Economy',
        ],
      },
    ],
  },
  {
    classLevel: 'Class 12',
    boards: ['CBSE', 'NCERT', 'ISC', 'State Board'],
    subjects: [
      {
        name: 'Physics',
        chapters: [
          'Electric Charges and Fields',
          'Electrostatic Potential and Capacitance',
          'Current Electricity',
          'Moving Charges and Magnetism',
          'Magnetism and Matter',
          'Electromagnetic Induction',
          'Alternating Current',
          'Electromagnetic Waves',
          'Ray Optics and Optical Instruments',
          'Wave Optics',
          'Dual Nature of Radiation and Matter',
          'Atoms',
          'Nuclei',
          'Semiconductor Electronics',
        ],
      },
      {
        name: 'Chemistry',
        chapters: [
          'Solutions',
          'Electrochemistry',
          'Chemical Kinetics',
          'The d- and f-Block Elements',
          'Coordination Compounds',
          'Haloalkanes and Haloarenes',
          'Alcohols, Phenols and Ethers',
          'Aldehydes, Ketones and Carboxylic Acids',
          'Amines',
          'Biomolecules',
        ],
      },
      {
        name: 'Mathematics',
        chapters: [
          'Relations and Functions',
          'Inverse Trigonometric Functions',
          'Matrices',
          'Determinants',
          'Continuity and Differentiability',
          'Application of Derivatives',
          'Integrals',
          'Application of Integrals',
          'Differential Equations',
          'Vector Algebra',
          'Three Dimensional Geometry',
          'Linear Programming',
          'Probability',
        ],
      },
      {
        name: 'Biology',
        chapters: [
          'Sexual Reproduction in Flowering Plants',
          'Human Reproduction',
          'Reproductive Health',
          'Principles of Inheritance and Variation',
          'Molecular Basis of Inheritance',
          'Evolution',
          'Human Health and Disease',
          'Microbes in Human Welfare',
          'Biotechnology: Principles and Processes',
          'Biotechnology and its Applications',
          'Organisms and Populations',
          'Ecosystem',
          'Biodiversity and Conservation',
        ],
      },
    ],
  },
  {
    classLevel: 'Class 9',
    boards: ['CBSE', 'NCERT', 'State Board'],
    subjects: [
      {
        name: 'Science',
        chapters: [
          'Matter in Our Surroundings',
          'Is Matter Around Us Pure',
          'Atoms and Molecules',
          'Structure of the Atom',
          'The Fundamental Unit of Life',
          'Tissues',
          'Motion',
          'Force and Laws of Motion',
          'Gravitation',
          'Work and Energy',
          'Sound',
          'Improvement in Food Resources',
        ],
      },
      {
        name: 'Mathematics',
        chapters: [
          'Number Systems',
          'Polynomials',
          'Coordinate Geometry',
          'Linear Equations in Two Variables',
          'Introduction to Euclid’s Geometry',
          'Lines and Angles',
          'Triangles',
          'Quadrilaterals',
          'Circles',
          'Heron’s Formula',
          'Surface Areas and Volumes',
          'Statistics',
        ],
      },
    ],
  },
  {
    classLevel: 'Class 11',
    boards: ['CBSE', 'NCERT', 'State Board'],
    subjects: [
      {
        name: 'Physics',
        chapters: [
          'Units and Measurements',
          'Motion in a Straight Line',
          'Motion in a Plane',
          'Laws of Motion',
          'Work, Energy and Power',
          'System of Particles and Rotational Motion',
          'Gravitation',
          'Mechanical Properties of Solids',
          'Thermodynamics',
          'Oscillations',
          'Waves',
        ],
      },
      {
        name: 'Chemistry',
        chapters: [
          'Some Basic Concepts of Chemistry',
          'Structure of Atom',
          'Classification of Elements and Periodicity in Properties',
          'Chemical Bonding and Molecular Structure',
          'Chemical Thermodynamics',
          'Equilibrium',
          'Redox Reactions',
          'Organic Chemistry – Some Basic Principles and Techniques',
          'Hydrocarbons',
        ],
      },
    ],
  },
];

export const OFFICIAL_NCERT_RESOURCES: StudyResource[] = [
  {
    id: 'ncert-sci-10-ch1',
    title: 'Chemical Reactions and Equations',
    book: 'NCERT Science Class 10',
    subject: 'Science',
    classLevel: 'Class 10',
    chapter: 'Chapter 1: Chemical Reactions and Equations',
    source: 'National Council of Educational Research and Training (NCERT Official)',
    description: 'Comprehensive study of balanced chemical equations, types of reactions (combination, decomposition, displacement, double displacement, redox), corrosion and rancidity.',
    summary: 'A complete chemical equation represents the reactants, products and their physical states symbolically. Chemical reactions are balanced in accordance with the Law of Conservation of Mass.',
    keyPoints: [
      'Law of Conservation of Mass: Mass can neither be created nor destroyed in a chemical reaction.',
      'Combination reaction: Two or more substances combine to form a single product: A + B -> AB.',
      'Decomposition reaction: A single reactant breaks down into simpler products using heat, light or electricity.',
      'Oxidation is gain of oxygen or loss of hydrogen. Reduction is loss of oxygen or gain of hydrogen.',
      'Rancidity is the oxidation of fats and oils in food, producing unpleasant smell and taste.',
    ],
    keyFormulas: [
      '2Mg(s) + O2(g) -> 2MgO(s)',
      'CaO(s) + H2O(l) -> Ca(OH)2(aq) + Heat',
      '2FeSO4(s) --[Heat]--> Fe2O3(s) + SO2(g) + SO3(g)',
    ],
    solvedExamples: [
      {
        question: 'Why is respiration considered an exothermic reaction?',
        solution: 'During digestion, carbohydrates are broken down into glucose. Glucose combines with oxygen in the cells of our body and provides energy: C6H12O6 + 6O2 -> 6CO2 + 6H2O + Energy.',
      },
    ],
    pdfUrl: 'https://ncert.nic.in/textbook/pdf/jesc101.pdf',
    externalLink: 'https://ncert.nic.in/textbook.php',
  },
  {
    id: 'ncert-sci-10-ch6',
    title: 'Life Processes',
    book: 'NCERT Science Class 10',
    subject: 'Science',
    classLevel: 'Class 10',
    chapter: 'Chapter 6: Life Processes',
    source: 'NCERT Textbook Archive',
    description: 'Fundamental processes essential for maintaining life: Nutrition (autotrophic and heterotrophic), Respiration, Transportation in humans and plants, and Excretion.',
    summary: 'Living organisms utilize life processes including nutrition, respiration, transportation of materials, and excretion of waste to maintain molecular structures and survive.',
    keyPoints: [
      'Photosynthesis equation: 6CO2 + 12H2O --[Light & Chlorophyll]--> C6H12O6 + 6O2 + 6H2O.',
      'Stomata regulate gas exchange and transpiration through guard cells.',
      'Aerobic respiration produces 38 ATP in mitochondria, while anaerobic respiration in human muscle generates lactic acid.',
      'Human heart has 4 chambers preventing mixing of oxygenated and deoxygenated blood.',
      'Nephron is the basic structural and functional filtration unit of the human kidney.',
    ],
    keyFormulas: [
      'Glucose (6C) -> Pyruvate (3C) in cytoplasm',
      'Pyruvate + O2 -> 6CO2 + 6H2O + 38 ATP (Mitochondria)',
      'Pyruvate (lack of O2) -> Lactic Acid + Energy (Muscles)',
    ],
    pdfUrl: 'https://ncert.nic.in/textbook/pdf/jesc106.pdf',
    externalLink: 'https://ncert.nic.in/textbook.php',
  },
  {
    id: 'ncert-sci-10-ch12',
    title: 'Electricity',
    book: 'NCERT Science Class 10',
    subject: 'Science',
    classLevel: 'Class 10',
    chapter: 'Chapter 12: Electricity',
    source: 'NCERT Official Portal',
    description: 'Electric current and circuit, electric potential and potential difference, Ohm’s law, resistance, factors affecting resistance, series and parallel circuits, electric power.',
    summary: 'Electric current is the flow of electric charges. Electric potential difference across two points is the work done per unit charge moving between those points.',
    keyPoints: [
      'Ohm’s law states V = I * R at constant temperature.',
      'Resistance R = ρ * (L / A), where ρ is resistivity in Ohm-meter.',
      'Series combination: Rs = R1 + R2 + R3; same current passes through all resistors.',
      'Parallel combination: 1/Rp = 1/R1 + 1/R2 + 1/R3; potential difference across each resistor is equal.',
      'Joule’s law of heating: H = I^2 * R * t.',
      '1 kWh = 3.6 × 10^6 Joules (commercial unit of electric energy).',
    ],
    keyFormulas: [
      'I = Q / t (Amperes)',
      'V = W / Q (Volts)',
      'V = I * R (Ohm’s Law)',
      'P = V * I = I^2 * R = V^2 / R (Watts)',
      'H = I^2 * R * t (Joule Heating)',
    ],
    solvedExamples: [
      {
        question: 'An electric lamp of resistance 20 Ω and a conductor of 4 Ω resistance are connected in series to a 6 V battery. Calculate the total circuit resistance and current.',
        solution: 'Total resistance R = 20 + 4 = 24 Ω. Current I = V / R = 6 V / 24 Ω = 0.25 A.',
      },
    ],
    pdfUrl: 'https://ncert.nic.in/textbook/pdf/jesc112.pdf',
    externalLink: 'https://ncert.nic.in/textbook.php',
  },
  {
    id: 'ncert-math-10-ch1',
    title: 'Real Numbers & Polynomials',
    book: 'NCERT Mathematics Class 10',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    chapter: 'Chapter 1 & 2: Real Numbers & Polynomials',
    source: 'NCERT Official Mathematics Publication',
    description: 'Fundamental Theorem of Arithmetic, irrationality proofs, zeroes of polynomials, and relationship between zeroes and coefficients of quadratic polynomials.',
    summary: 'Every composite number can be expressed (factorized) as a product of primes uniquely, apart from the order of prime factors.',
    keyPoints: [
      'Fundamental Theorem of Arithmetic guarantees unique prime factorization.',
      'HCF(a, b) * LCM(a, b) = a * b for any two positive integers.',
      'Proof by contradiction that √2, √3, √5 are irrational numbers.',
      'Quadratic polynomial ax^2 + bx + c: Sum of zeroes α + β = -b/a, Product α * β = c/a.',
    ],
    keyFormulas: [
      'HCF(a, b) × LCM(a, b) = a × b',
      'α + β = -b / a',
      'α × β = c / a',
      'p(x) = k [x^2 - (α + β)x + αβ]',
    ],
    pdfUrl: 'https://ncert.nic.in/textbook/pdf/jemh101.pdf',
    externalLink: 'https://ncert.nic.in/textbook.php',
  },
  {
    id: 'ncert-phys-12-ch1',
    title: 'Electric Charges and Fields',
    book: 'NCERT Physics Part 1 Class 12',
    subject: 'Physics',
    classLevel: 'Class 12',
    chapter: 'Chapter 1: Electric Charges and Fields',
    source: 'NCERT Department of Education in Science and Mathematics',
    description: 'Coulomb’s law, electric field lines, electric dipole, electric flux, Gauss’s law and its applications to uniformly charged thin spherical shell and infinite straight wire.',
    summary: 'Electric charge is quantized and conserved. Coulomb’s Law gives the force between two stationary point charges. Gauss’s law relates total electric flux through a closed surface to the net enclosed charge.',
    keyPoints: [
      'Quantization of charge: q = ± n*e, where e = 1.6 × 10^-19 C.',
      'Coulomb’s Law: F = (1 / 4πε0) * (|q1 * q2| / r^2) in vacuum.',
      'Electric field of a point charge: E = (1 / 4πε0) * (q / r^2).',
      'Electric dipole moment p = q * (2a) directed from negative to positive charge.',
      'Gauss’s law: ∮ E · dA = q_enclosed / ε0.',
    ],
    keyFormulas: [
      'F = (1 / 4πε0) × (q1 q2 / r^2) [ε0 ≈ 8.854 × 10^-12 C^2 N^-1 m^-2]',
      'E_axial = (1 / 4πε0) × (2p / r^3)',
      'E_equatorial = (1 / 4πε0) × (p / r^3)',
      'Φ = ∮ E · dA = q_in / ε0',
    ],
    pdfUrl: 'https://ncert.nic.in/textbook/pdf/leph101.pdf',
    externalLink: 'https://ncert.nic.in/textbook.php',
  },
  {
    id: 'ncert-chem-12-ch2',
    title: 'Solutions & Colligative Properties',
    book: 'NCERT Chemistry Part 1 Class 12',
    subject: 'Chemistry',
    classLevel: 'Class 12',
    chapter: 'Chapter 2: Solutions',
    source: 'NCERT Official Portal',
    description: 'Types of solutions, expression of concentration, Henry’s law, Raoult’s law, ideal and non-ideal solutions, colligative properties (RLVP, elevation in BP, depression in FP, osmotic pressure), van’t Hoff factor.',
    summary: 'Colligative properties depend solely on the ratio of the number of solute particles to solvent molecules in a solution, regardless of their identity.',
    keyPoints: [
      'Raoult’s Law for volatile liquids: P_total = p1° * x1 + p2° * x2.',
      'Henry’s Law: p = KH * x (solubility of gas in liquid).',
      'Elevation in boiling point: ΔTb = Kb * m.',
      'Depression in freezing point: ΔTf = Kf * m.',
      'Osmotic pressure: π = i * C * R * T.',
      'van ’t Hoff factor i accounts for association or dissociation of electrolytes.',
    ],
    keyFormulas: [
      'ΔTb = i × Kb × m',
      'ΔTf = i × Kf × m',
      'π = i × C × R × T',
      '(P° - P) / P° = i × x_solute',
    ],
    pdfUrl: 'https://ncert.nic.in/textbook/pdf/lech102.pdf',
    externalLink: 'https://ncert.nic.in/textbook.php',
  },
];
